### ISSUE TITLE
Clarification for subsection 3.2.3

### ISSUE THREAD

**Issue by palojos** [gamma-opt/optimisation-notes#16] opened 2022-02-03 09:53 UTC
In subsection 3.2.3 there is vector c without any clarification or context of what vector c represents in equation where reduced cost is derived.

Also in Definition 3.8 isn't c supposed to be defined without subscript B as objective value vector? 

To fix this, I would add clear definition that our objective function is vector c times x and after moving step d it has changed c times d (times is interpreted as inner product). 

And as last remark, when c subscript B is defined, it's defined as row vector, but used both as row and column vector.

I can provide pull request fixing at least technical issues.

**Comment by FabsOliveira** [comment] 2022-02-10 11:43
> In subsection 3.2.3 there is vector c without any clarification or context of what vector c represents in equation where reduced cost is derived.

> To fix this, I would add clear definition that our objective function is vector c times x and after moving step d it has changed c times d (times is interpreted as inner product).

That is a very good point. We should clearly state that c^\top x is the objective function.

> Also in Definition 3.8 isn't c supposed to be defined without subscript B as objective value vector?

That one should be c_B, but I think the association is confusing. The rewording could be "and let c_B be the objective function coefficients associated with the basis B" or something like that. 

> And as last remark, when c subscript B is defined, it's defined as row vector, but used both as row and column vector.

Indeed. In theory, all our vectors are column vectors, unless otherwise stated (normally using ^\top). The problem is that I often fail to keep my own convention and never made it explicit in the text. I think we could define c_B to be a column vector (defined with brackets, not parenthesis) so c_B^\top B^{-1} is the correct form. At least that should be the more frequent, but sometimes I let it slip when switching references.

Please go ahead and make a pull request! I would really appreciate it.

**Comment by FabsOliveira** [comment] 2022-02-15 13:48
Closed by #19

**Closed by FabsOliveira** 2022-02-15 13:48 UTC
